MEMORY
{
  RAM : ORIGIN = 0x80000000, LENGTH = 127M
  HEAP : ORIGIN = 0x87F00000, LENGTH = 1M
}

REGION_ALIAS("REGION_TEXT", RAM);
REGION_ALIAS("REGION_RODATA", RAM);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_STACK", RAM);
REGION_ALIAS("REGION_HEAP", HEAP);

/* Required for riscv-rt */
_hart_stack_size = 0x2000;
